overrides: bear-requirements.yaml

allow_generic_no_cover: true

nocover_file_globs:
  - .ci/*

nocover_regexes:
  # `.` can only be `#`
  - 'if .*:  . backwards compatible no results'

nocover_branch_regexes:
  # Allows retaining existing indentation
  # `.` can only be `#`
  - 'if True:  . no else'
